Romc method implementation
elfi-dev/elfi pull request #342
Opened 2020-12-08 20:38 UTC by givasile

Implementation of the [ROMC](http://proceedings.mlr.press/v108/ikonomov20a.html) framework. The implementation is presented analytically in my [dissertation](https://givasile.github.io/assets/pdf/edinburgh_thesis.pdf).

Some highlights of the implementation are:
- applying ROMC, solving the deterministic optimization problems using a gradient-based optimizer
- applying ROMC, solving the deterministic optimization problems with Bayesian Optimization (when gradients are not available)
- fitting a surrogate model for representing the neighbourhood around the optimal point
- a parallel-version of all algorithms for taking advantage of all CPU cores
- code design that preserves extensibility (i.e. allows the user to intervene on a specific part of the method, using its custom algorithm, without the rest of the method to collapse.)
- testing and documentation

Copyright: [Vasileios Gkolemis](https://givasile.github.io)

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD3 (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2021-02-10 14:38 UTC, hpesonen requested changes
Great work! You seem to be using print()-commands for following the execution. Could you turn relevant ones into  log-notifications using `logging` so that the user can control the console output more freely.  

There's also quite a bit of repeated code in `class BoDetereministic` - I can see why. I think we'll need to refactor `BayesianOptimization` and `BOLFI`, but we can do this in a separate PR as it can be quite a bit of additional work.

2021-02-10 15:04 UTC, givasile commented
> Great work! 

Thanks!

> You seem to be using print()-commands for following the execution. Could you turn relevant ones into log-notifications using `logging` so that the user can control the console output more freely.

Yes, I will make the change on a new commit asap. 
 
> There's also quite a bit of repeated code in `class BoDetereministic` - I can see why. I think we'll need to refactor `BayesianOptimization` and `BOLFI`, but we can do this in a separate PR as it can be quite a bit of additional work.

I also agree. I didn't want to touch `BOLFI` and `BayesianOptimization` on my own, for not destroying functionality needed by other methods. But since there is quite some overlapping, with some clever modification, `BoDeterministic` can be absorbed by `BayesianOptimization`. Since it is quite some work it is better to schedule it as a separate task in a new PR.

2021-02-17 13:10 UTC, givasile commented
- [x] print -> logging

2021-02-22 13:49 UTC, hpesonen approved these changes

2021-02-22 13:49 UTC, merged