Include basic arviz support
elfi-dev/elfi pull request #475
Opened 2024-02-01 13:45 UTC by hpesonen

#### Summary:
Added arvix dependency and a method for converting `elfi.Sample` object to  `arviz.InferenceData`

#### Please make sure

- You have read [contribution guidelines](https://elfi.readthedocs.io/en/latest/developer/contributing.html)
- You have updated CHANGELOG.rst
- You have listed the copyright holder for the work you are submitting (see next section)

If your contribution adds, removes or somehow changes the functional behavior of the package, please check that

- You have included or updated all the relevant documentation, including docstrings
- You have added appropriate functional and unit tests to ensure the new features behave as expected
- You have run `make lint`, `make docs` and `make test`

and the proposed changes pass all unit tests (check step 6 of CONTRIBUTING.rst for details)

#### Copyright and Licensing

Please list the copyright holder for the work you are submitting (this will be you or your assignee, such as a university or company):

By submitting this pull request, the copyright holder is agreeing to license the submitted work under the following licenses:
- Code: BSD3 (https://opensource.org/licenses/BSD-3-Clause)
- Documentation: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)

2024-03-13 23:24 UTC, uremes commented on elfi/methods/results.py
> +import arviz as az
this import should be moved to the next block (there's an error when i run `make lint`)

2024-03-19 12:56 UTC, uremes requested changes
this looks good. just need to fix the style error that i mentioned in the previous comment

2024-03-19 14:22 UTC, hpesonen commented on elfi/methods/results.py
> +import arviz as az
I think I need to modify our test suite. Github tests should flag these as well.

2024-03-19 14:27 UTC, hpesonen commented on elfi/methods/results.py
> +import arviz as az
btw, I don't get an error here with `make lint`. And looking at it, shouldn't it be where it is?

2024-03-23 00:31 UTC, uremes commented on elfi/methods/results.py
> +import arviz as az
true and i don't get an error now either

2024-03-23 00:31 UTC, uremes approved these changes

2024-03-24 17:00 UTC, merged